import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import SessionAppProvider from "./_components/SessionAppProvider";
import TanstackQueryClient from "./_components/TanstackQueryClient";
import { Toaster } from "@/components/ui/toaster";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <TanstackQueryClient>
          <SessionAppProvider>
            <Navbar />
            <main>{children}</main>
          </SessionAppProvider>
        </TanstackQueryClient>
        <Toaster />
      </body>
    </html>
  );
}
